services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sabemi
      POSTGRES_USER: sabemi
      POSTGRES_PASSWORD: sabemi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sabemi -d sabemi"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: src/SabemiTec.Api/Dockerfile
    environment:
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=sabemi;Username=sabemi;Password=sabemi"
      Webhook__ApiKey: ${WEBHOOK_API_KEY:-dev-local-key}
      Processing__SimulatedDelayMs: "2000"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./web
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  pgdata:
